### ISSUE TITLE
Add the chimera1n script

### ISSUE THREAD

**Issue by demhademha** [Watking01/bootm8#2]
**Describe the solution you'd like**

Could you add the chimera1n script as it would be very easy to run it 
**Additional context**

**Comment by SarKaa** [comment]
Of course I'll look into this as soon as possible
And also, could you test this for me once implemented, because my main jailbroken device is no longer using checkra1n, plus I am 100% against the Electra team and wouldn't even try using chimera1n

**Comment by demhademha** [comment]
Yeah sure, 
I’d give you some tips though 
1. Automatically delete /etc/ssh/known_hosts as it would be required to allow multiple devices to use chimera1n because normally, you have to delete that manually 
2. Could you please, please, add orca (scrrenreader support) as it would save me from jailbreaking my blind brother’s device each time

**Comment by SarKaa** [comment]
I just checked the chimera1n script, and turns out, it needs the host computer to have an internet connection, which jailm8 doesn't have, and if I did add it, it would make it too bulky, and would defeat the whole purpose of it.
As well as that, it also requires iproxy, which I have already tried to implement into jailm8, but it would break usbmuxd, which would render the whole project useless, so that's another obstacle.
Currently, with all the free time I have, I am trying to re-write coolstar's script to use the idevice to download the files instead, which would eliminate the need for a wifi connection. As per the iproxy problem, I am trying to implement ssh instead, which hopefully can be used in the chimera1n script instead.

**Comment by demhademha** [comment]
A tip from me, (a project that I’m also working on) is to use ish https://ish.app
This virtualises a Linux terminal on device with a full file system 
I am to use localssh (preinstalled after every checkra1n jailbreak at port 44) to automatically move the files over to the device. 
Perhaps we can work on this together? 
In addition, this wouldn’t require iProxy or libusbmuxd

**Comment by SarKaa** [comment]
I know about iSH, and having used it before, I also know that it only creates a virtual linux environment, what we need is an actual ssh to the device, not an app. The ssh connection you have is to a completely virtualised os, when we need a connection to the device, otherwise we would just end up bootstrapping iSH with chimera1n, which is arch linux I believe, which would do absolutely nothing to your main os

I am literally re-writing coolstar's script right now, and I believe that it should download the files to the device directly, and also bootstrap it from the script itself. 
And I am implementing an ssh client on jailm8, in order to help with this
I will update you on how this goes
edit: I have successfully rewritten the script into two seperate scripts, one that simply puts a file on your device that initiates chimera1n's parts of the script automatically, and the other that is put onto the device to download the files needed. I am compiling the final iso right now, and will upload it to github shortly

**Comment by demhademha** [comment]
... with ish, you can ssh into the device, and move files from ish to the device. And as a result,   You’d bootstrap the device. 
Try, with a checkra1n jailbroken device on ish “apk add ssh” 
And then 
“Ssh localhost -p44” which connects you to that device 
Then on the device, you can do things that you normally would on m.terminal ETC 
And in addition, you can transfer files :)

**Comment by SarKaa** [comment]
After rewriting coolstar's script and installing an ssh client to my base system, I present to you the first beta of jailm8 with chimera1n support
Link: https://github.com/SarKaa/jailm8/releases/tag/2.4
Again, this is still the very first beta, so you don't have to test it if you don't want to, but I would strongly warn against using this on your main device (you shouldn't risk jailbreaking it anyways), as this might result in unwanted behaviour
The tutorial for chimerain is here https://www.reddit.com/r/jailbreak/comments/g6g2jk/tutorial_the_simple_unofficial_guide_to/ , but you don't have to install curl or iproxy, or download any files, all you need to do is rootfs restore, rejailbreak and then run the command "chimera1n"

Be sure to get back to me if you do decide to try it

**Comment by SarKaa** [comment]
> ... with ish, you can ssh into the device, and move files from ish to the device. And as a result, You’d bootstrap the device.
> Try, with a checkra1n jailbroken device on ish “apk add ssh”
> And then
> “Ssh localhost -p44” which connects you to that device
> Then on the device, you can do things that you normally would on m.terminal ETC
> And in addition, you can transfer files :)

But you can do that without needing jailm8 at all, if you want an easy way to do this you can simply use the latest beta, but at your own risk, it shouldn't do anything, but coolstar's work hasn't always been the most stable or trustworthy

**Comment by SarKaa** [comment]
> Yeah sure,
> I’d give you some tips though
> 
> 1. Automatically delete /etc/ssh/known_hosts as it would be required to allow multiple devices to use chimera1n because normally, you have to delete that manually
> 2. Could you please, please, add orca (scrrenreader support) as it would save me from jailbreaking my blind brother’s device each time

Just reread this, and I am sorry to say that orca is impossible to implement into jailm8, as it requires a gui interface, which is the main thing jailm8 doesn't have, and in order to maintain its size, I cannot add a gui interface. 

I am absolutely helpless in this situation, and the only thing I can suggest is to use ubuntu or debian or any other linux operating systems, and install orca on it. That should make it much easier. I feel really bad that I can't personally do something about this, but if you need any help whatsoever, don't be afraid to ask, I will keep this issue open for you and you can ask me for help if you get stuck

**Comment by demhademha** [comment]
It’s ok,I’ll just do it for my brother
As for the chimera1n, I haven’t got round to it yet

**Comment by SarKaa** [comment]
ok just tell me when you try it if it works

**Comment by SarKaa** [comment]
Sorry but I just tried it and it didn’t work, I am working on a fix right now

**Comment by SarKaa** [comment]
Hey could you test this version: https://github.com/SarKaa/jailm8/releases/tag/2.4-2
It should have fixed the ssh problem, but I still need someone to test the actual chimera1n script, as I can't do that on unc0ver

**Comment by demhademha** [comment]
... 
a new version has been released called the procursus bootstrap

**Comment by SarKaa** [comment]
Yes I know I will look at the script when I have time, but I still need to make sure that this works

Edit: I just read the new odyssey-ra1n script, and I do believe it would be easier to use chimera1n from jaim8 first and then use the new script's migration feature to update it on device.
The new script is also impossible to re-write for jailm8, it definitely needs iproxy, and if I use ssh instead, I need to find the exact options, which won't work.
So to be clear, I would suggest using the jailm8 command "chimera1n" first, and then running the new script on-device.

**Comment by SarKaa** [comment]
Sorry but could you try this version, and then install the new procursus bootstrap from your device after running "chimera1n"
This new release should definitely work: https://github.com/SarKaa/jailm8/releases/tag/2.4-4

**Comment by SarKaa** [comment]
Sorry mate but ssh has way too many dependencies, and because of its minimal interface, they have to be installed manually, which is a pain, so I am closing this issue, and I would suggest using the new odyssey ra1n script on device itself
